version: '3'
services:
  postgres:
    restart: always
    image: sameersbn/postgresql:12-20200524
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=ifmo
      - DB_PASS=q1w2e3
      - DB_NAME=ifmo
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /tmp/docker/postgresql:/var/lib/postgresql